/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    appDir: true,
  },
  images: {
    domains: ['cloud.appwrite.io'],
  },
  env: {
    NEXT_PUBLIC_APPWRITE_ENDPOINT: process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT,
    NEXT_PUBLIC_APPWRITE_PROJECT_ID: process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID,
    NEXT_PUBLIC_APPWRITE_DATABASE_ID: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID,
    NEXT_PUBLIC_APPWRITE_VEHICLES_COLLECTION_ID: process.env.NEXT_PUBLIC_APPWRITE_VEHICLES_COLLECTION_ID,
    NEXT_PUBLIC_APPWRITE_MAINTENANCE_COLLECTION_ID: process.env.NEXT_PUBLIC_APPWRITE_MAINTENANCE_COLLECTION_ID,
    NEXT_PUBLIC_APPWRITE_EXPENSES_COLLECTION_ID: process.env.NEXT_PUBLIC_APPWRITE_EXPENSES_COLLECTION_ID,
    NEXT_PUBLIC_APPWRITE_STORAGE_BUCKET_ID: process.env.NEXT_PUBLIC_APPWRITE_STORAGE_BUCKET_ID,
  },
}

module.exports = nextConfig